import type { UiLanguage } from "@/lib/ui-settings-shared";

const copy = {
  en: {
    settings: "Settings",
    openSettings: "Open settings",
    appSettings: "App settings",
    interface: "Interface",
    language: "Language",
    theme: "Theme",
    german: "Deutsch",
    english: "English",
    light: "Light",
    dark: "Dark",
    savePreferences: "Save preferences",
    preferencesSaved: "Preferences saved.",
    preferencesFailed: "Preferences could not be saved.",
    apiConnections: "API connections",
    mailboxAccounts: "Mailbox accounts",
    languageDescription: "Switch the app language for the main interface.",
    themeDescription: "Use a clean dark workspace with higher contrast and no glass cards.",
    settingsIntro:
      "Manage providers, mailbox accounts, language, and theme from one place.",
    back: "Back",
    dashboard: "Dashboard",
    documentation: "Documentation",
    outreachEngine: "Outreach Engine",
    openContactTable: "Open Contact Table",
    addCompany: "Add company",
    addContact: "Add contact",
    leanMeanLeadFinderMachine: "Lean Mean Lead Finder Machine",
    search: "Search",
    enrich: "Enrich",
    findLeads: "Find leads",
    enrichContacts: "Enrich contacts",
    leadWorkspace: "Lead workspace",
    leadsAndContacts: "Leads and researched contacts",
    showingLatestThree: "Showing the latest 3 leads here. Open the workspace for the full list.",
    openTableView: "Open table view",
    systemLanguage: "System language",
    darkMode: "Dark mode",
    setupVault: "Setup vault",
    connectedMailboxes: "Connected mailboxes",
    openMailboxOperator: "Open mailbox operator",
    switchAccountsHint: "Rotate APIs, switch accounts, and connect sending mailboxes here.",
    runHistory: "Run history",
    expand: "Expand",
    allRuns: "All runs",
    closeRunHistory: "Close run history",
    universalSearch: "Universal search",
    searchLeadsAndContacts: "Search leads and contacts",
    closeUniversalSearch: "Close universal search",
    searchPlaceholder: "Search company, contact, website, niche, or email...",
    pipeline: "Pipeline",
    matches: "matches",
    contacts: "Contacts",
    moreContacts: "more contacts",
    noMatchesFound: "No matches found.",
    niche: "Niche",
    location: "Location",
    radiusMeters: "Radius in meters",
    safetyCap: "Safety cap",
    maxLeads: "Max leads",
    searchUntilNoPages: "Search until Google has no more pages",
    runExhaustiveSearch: "Run Exhaustive Search",
    runLeadSearch: "Run Lead Search",
    searchingGooglePlaces: "Searching Google Places...",
    searchingGooglePlacesLong: "Searching Google Places and paging through results...",
    scope: "Scope",
    onlyOneLeadSearchRun: "Only one lead-search run",
    allPendingLeads: "All pending leads",
    leadSearchRun: "Lead-search run",
    noLeadSearchRunYet: "No lead-search run yet",
    batchSize: "Batch size",
    retryFailedLeads: "Retry failed leads too",
    useOpenAiFallback: "Use OpenAI as fallback",
    runContactEnrichment: "Run Contact Enrichment",
    runningGeminiResearch: "Running Gemini research...",
    addContacts: "Add contacts",
    addContactsDescription: "Add one contact manually or import a CSV into existing companies.",
    manualContact: "Manual contact",
    company: "Company",
    selectCompany: "Select company",
    name: "Name",
    title: "Title",
    linkedin: "LinkedIn",
    instagram: "Instagram",
    twitterX: "Twitter / X",
    facebook: "Facebook",
    confidence: "Confidence",
    high: "High",
    medium: "Medium",
    low: "Low",
    saveContact: "Save contact",
    csvImport: "CSV import",
    csvFile: "CSV file",
    supportedColumns: "Supported columns",
    importContacts: "Import contacts",
    addCompanyTitle: "Add company",
    addCompanyDescription:
      "Create a company manually and optionally attach the first contact right away.",
    companyName: "Company name",
    address: "Address",
    website: "Website",
    nationalPhone: "National phone",
    internationalPhone: "International phone",
    optionalFirstContact: "Optional first contact",
    saveCompany: "Save company",
    manualCompaniesHint:
      "Manual companies become part of the same CRM, workspace, and outreach flow as imported leads.",
    noRunsYet:
      "No runs yet. Kick off a lead search and the machine will start building its own execution history.",
    noLeadsYet:
      "No leads yet. Run the first workflow with a niche and location to populate the table.",
    inbox: "Inbox",
    openInbox: "Open inbox",
    recentInboxActivity: "Recent inbox activity",
    noInboxActivity: "No new inbox activity yet.",
    dismissInboxItem: "Dismiss inbox item",
    unknownContact: "Unknown contact",
  },
  de: {
    settings: "Einstellungen",
    openSettings: "Einstellungen öffnen",
    appSettings: "Systemeinstellungen",
    interface: "Oberfläche",
    language: "Sprache",
    theme: "Design",
    german: "Deutsch",
    english: "Englisch",
    light: "Hell",
    dark: "Dunkel",
    savePreferences: "Einstellungen speichern",
    preferencesSaved: "Einstellungen gespeichert.",
    preferencesFailed: "Einstellungen konnten nicht gespeichert werden.",
    apiConnections: "API-Verbindungen",
    mailboxAccounts: "E-Mail-Konten",
    languageDescription: "Wechsle die App-Sprache für die Hauptoberfläche.",
    themeDescription: "Nutze einen klaren Dunkelmodus mit hohem Kontrast und ohne Glas-Karten.",
    settingsIntro:
      "Verwalte Provider, Mailboxen, Sprache und Theme an einem Ort.",
    back: "Zurück",
    dashboard: "Dashboard",
    documentation: "Dokumentation",
    outreachEngine: "Outreach Engine",
    openContactTable: "Kontakttabelle öffnen",
    addCompany: "Firma hinzufügen",
    addContact: "Kontakt hinzufügen",
    leanMeanLeadFinderMachine: "Lean Mean Lead Finder Machine",
    search: "Suche",
    enrich: "Anreicherung",
    findLeads: "Leads finden",
    enrichContacts: "Kontakte anreichern",
    leadWorkspace: "Lead-Arbeitsbereich",
    leadsAndContacts: "Leads und recherchierte Kontakte",
    showingLatestThree: "Hier werden die letzten 3 Leads angezeigt. Öffne den Workspace für die komplette Liste.",
    openTableView: "Tabellenansicht öffnen",
    systemLanguage: "Systemsprache",
    darkMode: "Dunkelmodus",
    setupVault: "API-Vault",
    connectedMailboxes: "Verbundene Mailboxen",
    openMailboxOperator: "Mailbox-Verwaltung öffnen",
    switchAccountsHint: "APIs wechseln, Konten austauschen und Versand-Mailboxen zentral verbinden.",
    runHistory: "Verlauf",
    expand: "Öffnen",
    allRuns: "Alle Läufe",
    closeRunHistory: "Verlauf schließen",
    universalSearch: "Universelle Suche",
    searchLeadsAndContacts: "Leads und Kontakte suchen",
    closeUniversalSearch: "Suche schließen",
    searchPlaceholder: "Firma, Kontakt, Website, Nische oder E-Mail suchen...",
    pipeline: "Pipeline",
    matches: "Treffer",
    contacts: "Kontakte",
    moreContacts: "weitere Kontakte",
    noMatchesFound: "Keine Treffer gefunden.",
    niche: "Nische",
    location: "Ort",
    radiusMeters: "Radius in Metern",
    safetyCap: "Sicherheitslimit",
    maxLeads: "Max. Leads",
    searchUntilNoPages: "Suchen, bis Google keine weiteren Seiten hat",
    runExhaustiveSearch: "Vollständige Suche starten",
    runLeadSearch: "Lead-Suche starten",
    searchingGooglePlaces: "Google Places wird durchsucht...",
    searchingGooglePlacesLong: "Google Places wird durchsucht und weitere Ergebnisse werden geladen...",
    scope: "Umfang",
    onlyOneLeadSearchRun: "Nur ein Lead-Suchlauf",
    allPendingLeads: "Alle wartenden Leads",
    leadSearchRun: "Lead-Suchlauf",
    noLeadSearchRunYet: "Noch kein Lead-Suchlauf",
    batchSize: "Batch-Größe",
    retryFailedLeads: "Fehlgeschlagene Leads erneut versuchen",
    useOpenAiFallback: "OpenAI als Fallback nutzen",
    runContactEnrichment: "Kontaktanreicherung starten",
    runningGeminiResearch: "Gemini recherchiert...",
    addContacts: "Kontakte hinzufügen",
    addContactsDescription:
      "Füge einen Kontakt manuell hinzu oder importiere eine CSV in bestehende Firmen.",
    manualContact: "Manueller Kontakt",
    company: "Firma",
    selectCompany: "Firma auswählen",
    name: "Name",
    title: "Titel",
    linkedin: "LinkedIn",
    instagram: "Instagram",
    twitterX: "Twitter / X",
    facebook: "Facebook",
    confidence: "Vertrauen",
    high: "Hoch",
    medium: "Mittel",
    low: "Niedrig",
    saveContact: "Kontakt speichern",
    csvImport: "CSV-Import",
    csvFile: "CSV-Datei",
    supportedColumns: "Unterstützte Spalten",
    importContacts: "Kontakte importieren",
    addCompanyTitle: "Firma hinzufügen",
    addCompanyDescription:
      "Erstelle eine Firma manuell und füge auf Wunsch direkt den ersten Kontakt hinzu.",
    companyName: "Firmenname",
    address: "Adresse",
    website: "Website",
    nationalPhone: "Nationale Telefonnummer",
    internationalPhone: "Internationale Telefonnummer",
    optionalFirstContact: "Optionaler erster Kontakt",
    saveCompany: "Firma speichern",
    manualCompaniesHint:
      "Manuelle Firmen werden Teil desselben CRM-, Workspace- und Outreach-Flows wie importierte Leads.",
    noRunsYet:
      "Noch keine Läufe. Starte eine Lead-Suche und das System baut seinen Verlauf automatisch auf.",
    noLeadsYet:
      "Noch keine Leads. Starte den ersten Workflow mit Nische und Ort, um die Tabelle zu füllen.",
    inbox: "Inbox",
    openInbox: "Inbox öffnen",
    recentInboxActivity: "Neueste Inbox-Aktivität",
    noInboxActivity: "Noch keine neue Inbox-Aktivität.",
    dismissInboxItem: "Inbox-Eintrag ausblenden",
    unknownContact: "Unbekannter Kontakt",
  },
} as const;

export function t(language: UiLanguage, key: keyof typeof copy.en) {
  return copy[language][key];
}
